# Generated by Django 4.2.5 on 2023-09-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shortenedurl_bitly_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='bitly_url',
        ),
    ]
